#!/bin/sh
export PHPRC=./php.ini
SUITE=$1
[ -z $SUITE ] && echo "please specify a folder with tests" && exit 0
[ ! -d $SUITE ] && echo "$SUITE must be a folder with php test files" && exit 0
shift
echo START SUITE:$SUITE
echo
CLEAN=1 SKIP_ACCOUNT=1 ./run-test tests/KazooTests/EmptyTestCase.php > /dev/null
result=0
for TEST in $(find $SUITE -name '*.php' | shuf)
do
        ./run-test $TEST
        if [ ! $? -eq 0 ]; then
             result=1
        fi
done
if [ ! $result -eq 0 ]; then
     echo ERROR SUITE:$SUITE
     echo
     exit 1
fi
echo COMPLETE SUITE:$SUITE
echo
exit 0
