#!/bin/sh
export PHPRC=./php.ini
CASES=$(find tests -path "*/${1}/*TestCase.php")
if [[ ! $CASES ]]; then
    echo "no cases found for app $1. make sure there is at least one *TestCase.php in the app. $CASES" && exit 0
fi
APP=$1
shift
echo START APP:$APP
result=0
for CASE in $CASES
do
./run-test "$CASE"
if [ ! $? -eq 0 ]; then
     result=1
fi
done
if [ ! $result -eq 0 ]; then
     echo ERROR APP:$APP
     exit 1
fi
echo COMPLETE APP:$APP
exit 0
