#!/bin/sh
export PHPRC=./php.ini
CASE=$1
TEST=$(find tests -name "${1}TestCase.php")
if [ ! -f $TEST ]; then
   echo "suite $1 not found. make sure there is a ${1}TestCase.php in the tests path" && exit 0
fi
shift
echo START CASE:$CASE "($TEST)"
echo
result=0
CLEAN=1 RESTART_PROFILE=1 ./run-test "$TEST"
if [ ! $? -eq 0 ]; then
     echo ERROR CASE:$CASE
     echo
     exit 1
fi
echo COMPLETE CASE:$CASE
echo
exit 0
