#!/bin/sh
export PHPRC=./php.ini
SUITE=$1
[ -z $SUITE ] && echo "please specify a folder with tests" && exit 0
[ ! -d $SUITE ] && echo "$SUITE must be a folder with php test files" && exit 0
shift
for TEST in $(find $SUITE -name '*.php' | shuf)
do
	echo
	echo TEST: $TEST
	vendor/bin/phpunit $* $TEST
	if [ ! $? -eq 0 ]
	then
		echo REPEAT TEST: $TEST
		sleep 5
		vendor/bin/phpunit $* $TEST
		if [ ! $? -eq 0 ]
		then
			echo REPEAT TEST CLEAN: $TEST
			CLEAN=1 vendor/bin/phpunit $* $TEST
			if [ ! $? -eq 0 ]
			then
				echo GIVE UP SUITE ON: $TEST
			fi
		fi
	fi
done
