FROM erlang:alpine
RUN apk --update add --no-cache --virtual .build-deps \
    git \
    dpkg-dev dpkg \
    gcc \
    g++ \
    libc-dev \
    linux-headers \
    make \
    autoconf \
    ncurses-dev \
    openssl-dev \
    unixodbc-dev \
    lksctp-tools-dev \
    tar \
    expat-dev \
    libxslt \
    wget bash curl \
    python \
    grep which


