site_name: Testing

pages:
- 'index.md'
- 'Make-Busy':
    - './README.md'
    - './doc/GETTING_STARTED.md'
    - './DEV-SESSION.md'
    - './CONTRIBUTING.md'
    - './TODO.md'
- 'Tests':
    - 'How to write tests': './doc/HOWTO.md'
- 'Docker':
    - './docker/README.md'
