<?php

// This file is generated by Composer
require_once 'vendor/autoload.php';

$client = new \Github\Client();
$client->authenticate("d7aeda7cc8417886ab0c0468de147ef54bdf3d1d", null,  Github\Client::AUTH_HTTP_TOKEN);
